services:
  - type: web
    name: productivityhub
    env: python
    buildCommand: "./venv/bin/python -m pip install -r requirements.txt"
    startCommand: "gunicorn productivityhub.wsgi:application"
    autoDeploy: true

    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: PYTHON_VERSION
        value: 3.11

      - key: DATABASE_URL
        fromDatabase:
          name: productivityhub-db
          property: connectionString

      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: productivityhub-db
    databaseName: productivityhub
    user: productivityhub_user
